# config/pro.yaml

# 生产环境配置
server:
  port: ":8080"
database:
  host: "prod-db-host"
  port: 5432
  user: "produser"
  password: "prodpassword"
  dbname: "proddb"
logger:
  path: "./logs/app.log"
  level: "error"
